[View in Colaboratory](https://colab.research.google.com/github/simrang02/machine_learning/blob/master/Assignment_15.ipynb)

In [0]:
#importing packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
from sklearn.datasets import load_digits
digits = load_digits()

In [0]:
X, y =  digits.data, digits.target

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
X = StandardScaler().fit_transform(X)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.30, random_state = 101)

In [0]:
from sklearn.decomposition import PCA

In [0]:
pca = PCA(n_components = 2)

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
reg = LogisticRegression()

In [80]:
reg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [0]:
predict = reg.predict(X_test)

In [0]:
from sklearn.metrics import *

In [83]:
accuracy_score(predict, y_test)

0.9740740740740741

In [84]:
print(confusion_matrix(predict, y_test))

[[53  0  0  0  0  1  1  0  0  0]
 [ 0 53  0  0  0  0  0  0  4  0]
 [ 0  0 49  0  0  0  0  0  0  0]
 [ 0  0  0 54  0  0  0  0  1  0]
 [ 0  0  0  0 59  0  0  2  0  0]
 [ 0  0  0  0  0 58  0  0  0  0]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  2  0  0  2  0  0  0 54  0]
 [ 0  0  0  0  0  0  0  0  0 47]]


In [85]:
print(classification_report(predict, y_test))

             precision    recall  f1-score   support

          0       1.00      0.96      0.98        55
          1       0.96      0.93      0.95        57
          2       1.00      1.00      1.00        49
          3       1.00      0.98      0.99        55
          4       0.97      0.97      0.97        61
          5       0.98      1.00      0.99        58
          6       0.98      1.00      0.99        45
          7       0.96      0.98      0.97        55
          8       0.92      0.93      0.92        58
          9       0.98      1.00      0.99        47

avg / total       0.97      0.97      0.97       540

